pipeline {
    agent {
        kubernetes {
         yaml '''
           apiVersion: v1
           kind: Pod
          spec:
            containers:
            - name: maven
              image: maven:alpine
              command:
              - cat
              tty: true
          '''
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
